; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ClaudeToZenn"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "nuits.jp"
#define MyAppURL "https://github.com/nuitsjp/ClaudeToZenn"
#define MyAppExeName "ClaudeToZenn.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{24254DEA-9933-461C-94A7-136CD235EA38}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=mysetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Files]
Source: "D:\ClaudeToZenn\host\ClaudeToZenn\bin\Release\net481\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\ClaudeToZenn\host\ClaudeToZenn\bin\Release\net481\ClaudeToZenn.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\ClaudeToZenn\host\ClaudeToZenn\bin\Release\net481\ClaudeToZenn.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\ClaudeToZenn\host\ClaudeToZenn\bin\Release\net481\Microsoft.Bcl.AsyncInterfaces.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\ClaudeToZenn\host\ClaudeToZenn\bin\Release\net481\Publish-Article.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\ClaudeToZenn\host\ClaudeToZenn\bin\Release\net481\System.Buffers.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\ClaudeToZenn\host\ClaudeToZenn\bin\Release\net481\System.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\ClaudeToZenn\host\ClaudeToZenn\bin\Release\net481\System.Numerics.Vectors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\ClaudeToZenn\host\ClaudeToZenn\bin\Release\net481\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\ClaudeToZenn\host\ClaudeToZenn\bin\Release\net481\System.Text.Encodings.Web.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\ClaudeToZenn\host\ClaudeToZenn\bin\Release\net481\System.Text.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\ClaudeToZenn\host\ClaudeToZenn\bin\Release\net481\System.Threading.Tasks.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\ClaudeToZenn\host\ClaudeToZenn\bin\Release\net481\System.ValueTuple.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
;Registry data from file jp.nuits.claude_to_zenn.reg
Root: HKCU; Subkey: "Software\Google\Chrome\NativeMessagingHosts\jp.nuits.claude_to_zenn"; Flags: uninsdeletekey; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "Software\Google\Chrome\NativeMessagingHosts\jp.nuits.claude_to_zenn"; ValueType: string; ValueName: ""; ValueData: "D:\ClaudeToZenn\host\ClaudeToZenn\bin\Debug\net481\manifest.json"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
;End of registry data from file jp.nuits.claude_to_zenn.reg

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

